### ISSUE TITLE
Update action to use node 16

### ISSUE THREAD

**Issue by christina-30** [OctopusDeploy/install-octopus-cli-action#379]
Hello, thanks for the convenient action! Unfortunately it is outdated, because it still uses the node12 runtime, can you please update to use node16?
![Screen Shot 2022-10-11 at 10 36 21 am](https://user-images.githubusercontent.com/112351798/194970267-8c795460-6b34-43f8-b6f6-9a0bfa8d9106.png)
@johnsimons @matt-richardson

**Comment by jbristowe** [comment]
Thanks, @christina-30! We'll update our actions to reflect this change.

**Comment by ann-mwangi** [comment]
Done as part of the[ latest release](https://github.com/OctopusDeploy/install-octopus-cli-action/releases/tag/v1.2.1).
