### ISSUE TITLE
Update readme for converting to 3.x

### ISSUE THREAD

**Issue by waynebrantley** [OctopusDeploy/install-octopus-cli-action#387]
I have spent quite a bit of time via trial and error to update to this new version.

For example:
- command is no longer 'octo' but is now 'octopus'
- command pack is no longer even an option?

It appears this is no really 'ready' as there are no docs on the new GO CLI and no docs on converting.  I think this should have been released as a beta or something.

For now, I have rolled back to the 1.x versions to get it to work.  Please advise on the desired path users should go.

**Comment by credfeto** [comment]
I've had the same experience and rolled back to 1.x after a few hours of trial and error.

**Comment by slewis74** [comment]
Apologies, these docs were supposed to have been released back in December but got delayed. We're in the process of getting this sorted out this week.
Similarly, pack also got delayed and will be shipping very soon. The team is working on [this PR](https://github.com/OctopusDeploy/cli/pull/201) at the moment.

**Comment by benPearce1** [comment]
Hi @waynebrantley and @credfeto,

The pack step has now been shipped, please note that it has been split in to two steps, [Nuget](https://octopus.com/docs/packaging-applications/build-servers/github-actions#create-nuget-package) and [Zip](https://octopus.com/docs/packaging-applications/build-servers/github-actions#create-zip-package).
We have also published docs for the new [Go CLI](https://octopus.com/docs/octopus-rest-api/cli).
