### ISSUE TITLE
Failed to Install Octopus CLI : Octopus CLI version not found: 1.7.1

### ISSUE THREAD

**Issue by MitchellPaff** [OctopusDeploy/install-octopus-cli-action#394]
**Describe the bug**
getting error message: Octopus CLI version not found: 1.7.1 when running install octopus CLI action on self-hosted linux runner

**To Reproduce**
Use the install octopus CLI action in a github action

**Expected behavior**
The latest Octopus CLI should install

**Screenshots**
![image](https://github.com/OctopusDeploy/install-octopus-cli-action/assets/77649372/f22d191f-9770-4849-8ab1-27ccbd7d7306)

**Additional context**
Self hosted Linux Runner

**Comment by martinsubx** [comment]
We are also experiencing the same issue. I've bumped the retries to 10 but it is still failing, please let me know if there is a workaround 
![image](https://github.com/OctopusDeploy/install-octopus-cli-action/assets/142394164/d95cf22f-5649-4b12-85f4-53dbb986fa23)

**Comment by MitchellPaff** [comment]
looks to be resolved now.
